[package]
name = "zabbix-lld-ws"
version = "0.1.0"
authors = ["Eugene Lebedev <duke.tougu@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
